# Generated by Django 2.0.4 on 2018-07-16 07:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=4, unique=True)),
                ('class_level', models.CharField(choices=[('BG', 'Beginner'), ('IM', 'Intermediate'), ('AD', 'Advanced')], default='BG', max_length=2)),
                ('class_timing', models.TimeField()),
                ('class_day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[0-9]{10}', 'Enter a valid mobile number without country code example:5199816450 (length must be 10)')])),
                ('email', models.EmailField(max_length=254)),
                ('street_name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('province', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('MS', 'Membership'), ('TE', 'Test'), ('PP', 'Product Purchase')], default='MS', max_length=2)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('WHITE', 'WHITE'), ('YELLOW', 'YELLOW'), ('HALF GREEN', 'HALF GREEN'), ('GREEN', 'GREEN'), ('HALF BLUE', 'HALF BLUE'), ('BLUE', 'BLUE'), ('HALF RED', 'HALF RED'), ('RED', 'RED'), ('HALF BLACK', 'HALF BLACK'), ('BLACK', 'BLACK')], default='WHITE', max_length=15)),
                ('date_achieved', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('date_joined', models.DateField()),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[0-9]{10}', 'Enter a valid mobile number without country code example:5199816450 (length must be 10)')])),
                ('email', models.EmailField(max_length=254)),
                ('street_name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('province', models.CharField(max_length=40)),
                ('is_parent', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='0', max_length=3)),
                ('rank', models.CharField(choices=[('WHITE', 'WHITE'), ('YELLOW', 'YELLOW'), ('HALF GREEN', 'HALF GREEN'), ('GREEN', 'GREEN'), ('HALF BLUE', 'HALF BLUE'), ('BLUE', 'BLUE'), ('HALF RED', 'HALF RED'), ('RED', 'RED'), ('HALF BLACK', 'HALF BLACK'), ('BLACK', 'BLACK')], default='WHITE', max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='progress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karate.Student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karate.Student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karate.Class'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karate.Student'),
        ),
    ]
