# Generated by Django 2.0.4 on 2018-07-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karate', '0002_auto_20180716_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_day',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='MON', max_length=3),
        ),
    ]
