# Generated by Django 2.0.4 on 2018-07-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karate', '0003_auto_20180716_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestclass',
            name='class_day',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='MON', max_length=3),
        ),
    ]
